recognai/biome-text

src/biome/allennlp/commands/explore/app.py, src/biome/allennlp/commands/explore/explore.py
@dcfidalgo could you check it works properly with an already prediction explore? Thanks
=> chore: upgrade UI

src/biome/allennlp/commands/predict/predict.py
Just removes the deprecated predict code.
=> remove deprecated predict

src/biome/allennlp/commands/explore/explore.py
Small refactoring of the explore command so we can use it better outside of the package (for evo for example).
=> refactor the explore command to match the other commands

src/biome/allennlp/commands/serve/serve.py
make it more accessible from outside of the package (see #21)
=> refactor the serve command to match the other commands

src/biome/allennlp/commands/helpers.py, src/biome/allennlp/commands/learn/learn.py, src/biome/allennlp/commands/vocab/vocab.py, src/biome/allennlp/models/sequence_classifier.py, tests/allennlp/commands/test_helper.py
I merge this branch now, it contains an important bug fix for the master branch.
I tested the new BiomeConfig class and could not find any issues so far.
=> Rewrite biome2allennlp config

README.md, environment.yml, setup.py, src/biome/data/sources/readers.py, tests/allennlp/predictors/test_default_base_predictor.py, tests/data/sources/test_es_reader.py, tests/data/sources/test_example_preparator.py
This PR includes some maintenance changes
=> Refactor: clean dependencies and tests

src/biome/data/sources/readers.py
This PR includes datasource json reader capabilities for flatten nested json objects. This functionality is enabled using `flatten` flag in configuration: 
```yaml
format: json
path: my/dataset.json
flatten: true
```
=> feat(data): include flatten flag when reading json data

src/biome/allennlp/dataset_readers/sequence_classifier_dataset_reader.py, src/biome/data/sources/datasource.py
This PR keeps the `forward_dataframe`/`instances` as `dask.DataFrame`/`dask.Series` until we lazily iterate over it with `iteritems`.
=> Pandas df to dask df

src/biome/text/models/base_model_classifier.py, src/biome/text/models/similarity_classifier.py
This PR makes the `SimilarityClassifier` inherit from the `BaseModelClassifier`.
This means that it now works with `ListField`s as well.
The only difference to the `SequencePairClassifier` model, is that the `SimilarityClassifier` adds another term to the loss which is a function of the cosine similarity of the two records.
I tried to unify the `SimilarityClassifier` and the `SequencePairClassifier`, but i saw that there would be too many changes necessary for the `SequencePairClassifier` model, so i left the two models separated.
@frascuchon @dvsrepo I also added an explicit exception if a multifield_seq2seq encoder is added in the `BaseModelClassifier`, since there is a TODO, that this is not working ... Is this still true?
I tested the two models with my synthetic language data set, …
=> Adapt the `SimilarityClassifier`

src/biome/text/commands/explore/explore.py, src/biome/text/commands/helpers.py, src/biome/text/environment.py, tests/text/commands/test_helper.py, tests/text/models/base_classifier.py, tests/text/pipelines/sequence_classifier_test.py
A simple PR for refactoring the use of environment variables by defining a new python module where all environment variables used in project should be defined
=> define a environment module for all env vars definitions

src/biome/text/commands/learn/learn.py
This PR is related with [Pitch#25] (https://gitlab.com/recognai-team/team/issues/25)
The idea is if, an output folder is reused for different experiments, the previous generated  vocabulary will be reused for the training process. This make ease fix errors on model or trainer declarations.
The user is responsible of reuse the output data between compatible experiments
=> reuse vocab for experiments

src/biome/text/models/__init__.py, src/biome/text/models/mixins.py, src/biome/text/models/multifield_bimpm.py, src/biome/text/pipelines/__init__.py, src/biome/text/pipelines/multifield_bimpm.py, tests/text/pipelines/test_multifield_bimpm.py
This PR introduces a multifield BiMpm model. I tested it with my language data set and it seems to work quite well, i will add the experiment to the `biome-classifiers` repo as soon as possible.
Since this model is very specific to DZ Bank / Uniserv data (several records per golden record), i am not entirely sure if we want to include it in the library. We could also move it to our private DZ Bank repo and then load it via the `--include-package` argument.
@frascuchon @dvsrepo what do you think?
=> Multifield bimpm model

setup.py, src/biome/__init__.py
@frascuchon This is the change we talked about yesterday.
=> switch to python3 namespace package

src/biome/text/commands/serve/serve.py, src/biome/text/pipelines/pipeline.py, tests/text/pipelines/sequence_classifier_test.py
This should close #107
Need to include:
- parameterizable enable/disable behaviour
- parameterizable output path 
- add tests and checks
- check elasticsearch ingestions are ready for annotate
=> save pipeline predictions to file

src/biome/text/pipelines/_impl/allennlp/dataset_readers/configurable_input_datasource_reader.py
This PR includes a new datasource reader with basic configuration for model "inputs" and "outpus", and will be the first step for for achieve the new pipeline definition
=> new configurable input datasource reader

examples/1.text_classifier/text_classifier.py, examples/1.text_classifier/text_interpret.py, examples/1.text_classifier/trainer.yml, examples/2.document_classifier/doc_interpret.py, examples/2.document_classifier/document_classifier.py, examples/2.document_classifier/trainer.yml, examples/3.email_classifier/email_classifier.py, examples/3.email_classifier/trainer.yml, examples/4.language_model/classifier_from_scratch.py, examples/4.language_model/configs/trainer.yml, examples/4.language_model/finetune_classifier.py, examples/4.language_model/pretrain_lm.py, examples/5.ner/configs/trainer.yml, examples/5.ner/train_ner.py, examples/Untitled.ipynb, examples/token_classifier_from_text_classification.py, src/biome/text/api_new/__init__.py, src/biome/text/api_new/configuration.py, src/biome/text/api_new/constants.py, src/biome/text/api_new/helpers.py, src/biome/text/api_new/modules/encoders/__init__.py, src/biome/text/api_new/modules/heads/language_modelling.py, src/biome/text/api_new/pipeline.py
This PR define a `TrainerConfiguration`  class used for setup the `pipeline.train` method.
=> Training attributes as configuration class

src/biome/text/api_new/configuration.py, src/biome/text/api_new/featurizer.py
Just some improvements to defaults and docs I have while writing a tutorial for a tweet classifier
=> chore: improve defaults and docs featurizer and configuration

src/biome/text/_impl_model.py
=> fix(train): evaluate test data when a test dataset exists

src/biome/text/_helpers.py, src/biome/text/configuration.py
=> fix serialized models and lr logging training params

.gitignore, src/biome/text/_configuration.py, src/biome/text/_helpers.py, src/biome/text/_impl_model.py, src/biome/text/backbone.py, src/biome/text/modules/heads/bimpm_classification.py, src/biome/text/modules/heads/classification/defs.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/doc_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/record_classification.py, src/biome/text/modules/heads/text_classification.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py
=> refactor: rename model to backbone encoder

examples/1.text_classifier/text_classifier.py, src/biome/text/pipeline.py
=> fix(logging): enable/disable allennlp logging for training

src/biome/text/_configuration.py, src/biome/text/_impl_model.py, src/biome/text/_model.py, src/biome/text/pipeline.py
=> fix(head): set head and update related attrs

.travis.yml, Makefile, src/biome/text/about.py
=> feat(ci): configure pypi and test pypi

docs/docs/documentation/readme.md
=> doc: update instalation docs

src/biome/text/_helpers.py, src/biome/text/backbone.py, src/biome/text/errors.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py
=> feat: hide backbone features and allow disable tokenization

docs/guides/dev.contribution.HOWTO.md, docs/guides/releases.HOWTO.md
This PR include guides for:
- HOWTO create a new release
- HOWTO make code contribution
Both are proposal and we can discuss under this PR 
Closes #163
=> doc: add howto guides

src/biome/text/_model.py
=> fix: drop allennlp loggin handler initialization

.travis.yml, docs/.templates/html.mako, docs/docs/.vuepress/theme/styles/index.styl
=> fix markdown heading in template

docs/docs/.vuepress/theme/components/AlgoliaSearchBox.vue, docs/docs/.vuepress/theme/components/Navbar.vue
=> Custom Algolia searchBox

examples/1.text_classifier/text_classifier.py, examples/2.document_classifier/document_classifier.py, src/biome/text/_configuration.py, src/biome/text/pipeline.py
=> feat(train): drop verbose param and enable train logging

src/biome/text/_model.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/doc_classification.py, src/biome/text/modules/heads/text_classification.py
This PR is just a small refactor as discussed yesterday.
=> rename `prediction_explain` -> `explain_prediction`

README.md
=> docs: include installation details in main README.md

src/biome/text/modules/heads/classification/defs.py
This PR should solve #145 
@dvsrepo wants to do a test before merging this one.
=> remove numpy from ClassificationHead to make it GPU compatible

src/biome/text/pipeline.py
=> feat: include prediction logging and cache initialization

src/biome/text/_model.py, src/biome/text/pipeline.py
=> feat(train): restore disabled as default and restore vocab when enabled

src/biome/text/_model.py, src/biome/text/backbone.py, src/biome/text/configuration.py, src/biome/text/featurizer.py, src/biome/text/vocabulary.py
=> refactor(config): using words and chars config classes instead of dicts

examples/2.document_classifier/document_classifier.py, examples/2.document_classifier/document_classifier.yaml, src/biome/text/backbone.py, src/biome/text/tokenizer.py
=> feat: record tokenization with sentence segmentation

src/biome/text/modules/heads/language_modelling.py
Fixes a missing renaming of word level features
=> fix(feature): lm word level feature reference

docs/docs/.vuepress/config.js, docs/docs/.vuepress/theme/components/AlgoliaSearchBox.vue, docs/docs/.vuepress/theme/components/PageNav.vue, docs/docs/.vuepress/theme/components/search-orange.svg, docs/docs/.vuepress/theme/components/search.svg, docs/docs/.vuepress/theme/styles/index.styl, docs/docs/.vuepress/theme/styles/palette.styl
=> Fix nav links styles

src/biome/text/data/datasource.py, tests/text/data/test_csv_source.py
=> refactor: class DataSource cleanup

src/biome/text/_model.py, src/biome/text/pipeline.py
Also save trained models without pretrained embedding references.
=> fix(embedding): mock word features for empty vocab

examples/1.text_classifier/text_classifier.py, examples/1.text_classifier/text_classifier.yaml, examples/1.text_classifier/trainer.yml, examples/2.document_classifier/trainer.yml, examples/3.email_classifier/trainer.yml, examples/5.ner/configs/trainer.yml, setup.py, src/biome/text/_helpers.py, src/biome/text/_model.py, src/biome/text/backbone.py, src/biome/text/configuration.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/doc_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/record_classification.py, src/biome/text/modules/heads/record_pair_classification.py, src/biome/text/modules/heads/text_classification.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/modules/specs/defs.py, src/biome/text/pipeline.py, src/biome/text/text_cleaning.py, src/biome/text/tokenizer.py, tests/text/modules/heads/test_record_pair_classification.py
This PR applies analysis described [here](https://github.com/recognai/biome-text/pull/189) for a fully functional allennlp 1.0 integration.
Current version of allennlp is a release candidate, so, changes could be required.
We need integrate [this PR](https://github.com/recognai/biome-text/pull/218) before apply this PR
=> Upgrade to allennlp 1.0

tests/integration/resources/business.cat.2k.train.csv, tests/integration/resources/business.cat.2k.valid.csv, tests/integration/test_text_classification.py
This PR adds an integration test using the `TextClassification` head.
On my machine it takes <1 min and the numbers are reproducible.
It covers only a small part of the functionality, but with this test we would have caught the embedding bug for example.
The idea is that with time we extend the test to cover more functionalities, and maybe it can serve as blue print for other integration tests.
=> integration test for the text classification

src/biome/text/_model.py, src/biome/text/configuration.py, src/biome/text/featurizer.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/tokenizer.py
=> feat: add tokenization info on explain

setup.py, src/biome/text/cli/explore.py, src/biome/text/cli/train.py
This PR makes some minimal changes in commands cli.
=> refactor: command cli revision

src/biome/text/modules/specs/defs.py, tests/text/modules/specs/test_component_specs.py
=> fix(specs): always include type to component spec

src/biome/text/configuration.py, tests/text/test_configuration.py
=> fix(features): create embedder safety whithout word features

src/biome/text/modules/heads/classification/record_pair_classification.py
This adds a check for the sizes of the two records with an descriptive exception.
I also updated the doc string as discussed.
=> Add descriptive exception to RecordPairClassification.explain_prediction()

src/biome/text/pipeline.py
@frascuchon Is the `__prepare_experiment_folder` method still necessary?
I found that if i wanted to train the model a little bit more with `restore=True`, all the metrics from the first training run were gone. Could we just delete the output folder if restore=False and keep it if restore=True?
=> remove output folder if not `restore`

ui/src/components/elements/filters/FilterConfusionMatrix.vue
=> Closes #272

docs/docs/.vuepress/config.js, docs/docs/.vuepress/theme/layouts/Layout.vue
new footer
collapse sidebar levels
=> new footer

src/biome/text/pipeline.py
This batch size make explore process more resilient under low connection conditions
=> chore: adjust batch size for low connections

ui/src/assets/scss/apps/classifier/record.scss, ui/src/assets/scss/base/base.scss
fix width overflow
fix styles override
=> fix html in record

docs/docs/documentation/tutorials/Training_a_text_classifier.ipynb
trying to fix the tutorial test fail
=> ignore output of create_vocab cell

docs/docs/.vuepress/theme/components/Navbar.vue, docs/docs/.vuepress/theme/styles/code-colors.styl, docs/docs/.vuepress/theme/styles/index.styl, docs/docs/documentation/tutorials/Training_a_sequence_tagger_for_Slot_Filling.ipynb, docs/docs/documentation/tutorials/Training_a_text_classifier.ipynb
=> fix ui styles

docs/docs/documentation/readme.md
=> fix docs ref biome.text installation

Makefile, README.md
A minimal change for install from sources, making explicit the build web statics resources phase.
=> Documentation: install from sources

src/biome/text/helpers.py, src/biome/text/modules/heads/classification/classification.py
Just a small revision of the doc strings with one renaming.
=> Small review of doc strings

src/biome/text/pipeline.py
Adds fallback mechanism to pipeline clone when  deepcopy fails.
Note: This PR references pretrained model works
=> feat(pipeline): enable pipeline clone

src/biome/text/backbone.py, src/biome/text/featurizer.py
=> clean-up unused featurize methods

src/biome/text/loggers.py
For parallels train executions, fetching/creating the mlflow experiment information could brings race conditions that make logger crash. 
This PR includes mechanisms to mlflow logger to fetch/create experiment with retries, that could mitigate those errors in such scenarios.
=> fix(mlflow): try to fetch experiment info with retries

src/biome/text/loggers.py
Wraps all kind of exceptions for mlflow logger retries
=> fix(mlflow-logger): wraps common exception on retries

src/biome/text/_model.py, src/biome/text/pipeline.py, tests/text/test_pipeline_model.py
This PR includes a new method that will apply explain over a prediction batch
=> feat(pipeline): enable explain batch predictions

setup.py, src/biome/text/_helpers.py
Using batch methods for data exploration
=> refactor: explore using batch prediction

src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/helpers.py, src/biome/text/loggers.py, tests/text/test_loggers.py
This PR makes a better tracking of  pipeline & trainer parameters for mlflow UI integration
=> Feature: flatten mlflow parameters

src/biome/text/pipeline.py, tests/text/test_pipeline_datasets.py
This PR fixes fine tuning training when fine-tuned pipeline differs from original trained.
=> fix(pipeline): set copied pipeline state from loaded model instead of persisted one

docs/docs/README.md
=> update Home copy

src/biome/text/helpers.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py, tests/text/modules/heads/test_token_classification.py
This PR lets the TokenClassification head accept span labels as well as tag labels.
Still WIP, i think the current test fail is not related to the changes, have to test more tomorrow.
=> Accept spans for the TokenClassification task

docs/docs/documentation/tutorials/Hyperparameter_optimization_with_Ray_Tune.ipynb, docs/docs/documentation/tutorials/Training_a_sequence_tagger_for_Slot_Filling.ipynb, docs/docs/documentation/tutorials/Training_a_text_classifier.ipynb
Numeration of the tutorials into the biome website should be changing to match the order of difficulty.
=> Numeration of tutorials changed

src/biome/text/helpers.py, src/biome/text/modules/configuration/__init__.py, src/biome/text/modules/configuration/allennlp_configuration.py, src/biome/text/modules/heads/__init__.py, src/biome/text/modules/heads/classification/relation_classification.py, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_relation_classifier.py
This PR adds a basic relation classifier. Current caveats:
- We add an `entity_embedder` layer based on the `Embedding` allennlp layer. This works fine but we need to manually configure the `num_embeddings` param in the config, which somehow breaks current inference we have for embeddings (made possible by TextFieldEmbedders) and thus the extensibility of this embedding layer when further training.
- We manually concat this feature with the embedder output in the forward pass due to the same reason of not integrating this feature into the TextFieldEmbedder machinery.
I'm ok with this for now, but as discussed with @frascuchon this opens up the question of how to add other features to the `features` configuration (beyond current token text features). Both caveats will be avoided if we …
=> Baseline sentence/paragraph level relation classifier

src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_token_classification.py, tests/text/test_loggers.py
This PR should solve current fail of our pipeline.
=> Bugfix in the `TokenClassification` introduced in PR #370

ui/src/components/common/elasticsearch/queries.js
=> fix(ui): show confidence content in filter

.gitignore, setup.py, src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/helpers.py, src/biome/text/hpo.py, src/biome/text/pipeline.py, tests/text/test_hpo.py
This PR simplify ray.tune hpo integration
=> feat: hpo components

docs/docs/documentation/tutorials/3-Hyperparameter_optimization_with_Ray_Tune.ipynb, setup.py, src/biome/text/hpo.py, src/biome/text/loggers.py, src/biome/text/pipeline.py
This PR updates our HPO tutorial to include the usage of our HPO stuff.
It also fixes some small issues mentioned by @dvsrepo in the past, and improves a bit the `WandBLogger`.
=> Update HPO tutorial

src/biome/text/dataset.py
=> Expose most of HF Dataset methods to our Dataset for convenience

src/biome/text/dataset.py
Just copying over a few more methods to our Dataset.
=> Add format methods for nicer visualization via pandas

src/biome/text/dataset.py
Just adding this parameter in case the computed default value is a bad choice.
=> Add num_proc parameter to to_instances method

src/biome/text/modules/heads/classification/record_pair_classification.py
=> small annotation fix

src/biome/text/explore.py, src/biome/text/modules/heads/classification/classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/task_head.py, src/biome/text/modules/heads/token_classification.py, tests/text/test_pipeline_explore.py
This PR adds to explore information the whole pipeline configuration
=> Explore includes pipeline config

docs/docs/documentation/tutorials/1-Training_a_text_classifier.ipynb
Fixes the first tutorial on Colab and updates it to use the new `Dataset` class.
=> Fix and update first tutorial to use newest pip version and Datasets

docs/docs/documentation/tutorials/2-Training_a_sequence_tagger_for_Slot_Filling.ipynb, src/biome/text/dataset.py
This fixes the second tutorial and adapts it to the new Dataset
=> Fix and adapt second tutorial to Dataset

src/biome/text/dataset.py
Adds a new class method to `Dataset` allowing to create a single Dataset from a list of datasets.
=> Add a `from_datasets` class method to `Dataset`

src/biome/text/explore.py
This PR should fixes explore UI problems
=> fix(explore): do not stringfy predictions

src/biome/text/pipeline.py, tests/text/test_pipeline_evaluate.py
Small addition to the evaluate method.
=> Add cuda_device parameter to evaluate method

.github/workflows/tests.yml, src/ci/before_install.sh
I will quickly add this simple Github action to have the essentials covered, that is the tests.
Stuff missing:
- build docs
- deployment
=> Add Github action for our tests

src/biome/text/dataset.py, src/biome/text/helpers.py, tests/text/test_dataset.py
This PR allows select which field will be loaded from elasticsearch documents.
=> feat(ds): select es dataset features

.github/workflows/ci.yml, docs/docs/.vuepress/config.js, docs/docs/.vuepress/theme/components/Sidebar.vue, docs/docs/.vuepress/theme/components/Versions.vue, docs/package.json
This should be a first working step to add versioning to our docs.
=> Add versioning to the docs

docs/docs/.vuepress/theme/components/Versions.vue, docs/docs/.vuepress/theme/styles/index.styl, docs/package.json, ui/package.json
adapt versioning component to biome UI
=> style versioning component

docs/docs/.vuepress/theme/components/Sidebar.vue, docs/docs/.vuepress/theme/components/Versions.vue, docs/docs/.vuepress/theme/styles/index.styl
prevent sidebar links overflow
=> fix sidebar nav height

setup.py
Quick revision of our dependencies.
=> Revise dependencies

docs/docs/documentation/community/3-developer_guides.md
Small addition to the release guide regarding the algolia search
=> Add algolia search update to release guide

docs/docs/documentation/tutorials/3-Hyperparameter_optimization_with_Ray_Tune.ipynb
=> Docs: Add tip about creating an Analysis object from a directory

src/biome/text/cli/serve.py
A small improvement of the `biome serve` cli command.
=> Include a host parameter for the `biome serve` cli

docs/docs/documentation/basics.md, setup.py, src/biome/text/_helpers.py, src/biome/text/configuration.py, src/biome/text/hpo.py, src/biome/text/loggers.py
These changes are related to some smalish improvements made during the ProfNER challenge. 
This PR also includes a fix in the documentation.
=> Improvements from ProfNER

src/biome/text/mlflow_model.py, src/biome/text/pipeline.py, src/biome/text/trainer.py, tests/text/test_pipeline_to_mlflow.py
This PR improves the `Pipeline.to_mlflow()` functionality. Now the models get uploaded to the MLflow artifact storage and get automatically downloaded when used as mlflow model.
=> Feat:improve mlflow model

src/biome/text/model.py, src/biome/text/pipeline.py
This PR sets the stage for loading our Pipeline from pl checkpoints.
Now it starts to become a bit ugly to maintain both `allennlp.models.Model` and `pl.LightningModule`, mainly because of the way you serialize/load them. My idea is to support both ways until all current features are implemented with the lightning trainer, make a last release supporting the old `model.tar.gz`, and then get rid of the `allennlp.models.Model` and clean up the code. @dvsrepo @frascuchon objections?
=> Allow loading model via `LightningModule.load_from_checkpoint`

src/biome/text/configuration.py, src/biome/text/model.py, src/biome/text/trainer.py, tests/text/test_trainer.py
This PR concerns the new lightning trainer and adds the feature of loading the best weights by default at the end of the training, and saves the pipeline to an output dir if specified.
=> Feat lightining trainer: Load best weights + save pipeline to output dir

src/biome/text/configuration.py, src/biome/text/trainer.py, tests/text/test_trainer.py
By default, use a GPU if available. #543
=> LightningTrainer: Train on gpu by default if available

src/biome/text/__init__.py, src/biome/text/configuration.py, src/biome/text/dataset.py, src/biome/text/features.py, src/biome/text/hpo.py, src/biome/text/model.py, src/biome/text/trainer.py, tests/text/test_hpo.py
This PR belongs to #543 and implements the lightning trainer in our `TuneExperiment`.
Next steps: 
- change our docs/tutorials
- add deprecation warnings for the allennlp trainer
- make a last release where we support both trainers, after that i will begin to remove the allennlp trainer and finally bump up the version to allennlp~2.0
=> Feat: tune experiment with new lightning trainer

src/biome/text/__init__.py, src/biome/text/dataset.py, src/biome/text/trainer.py, tests/text/test_trainer.py
Important bugfix in the new trainer + improve logging
=> Bugfix: move vocab creation before optimizer creation

src/biome/text/__init__.py, src/biome/text/model.py, src/biome/text/pipeline.py
This PR simplifies a bit the logging and improves it for the new lightning trainer.
=> Improve logging

src/biome/text/cli/train.py
Adds the most basic training as cli command
=> Add back a working implementation of the train cli command

src/biome/text/pipeline.py, tests/text/test_pipeline_to_mlflow.py
=> Add version to biome.text dependency in the mlflow model conda env

src/biome/text/modules/heads/token_classification.py
When logits become nans, the current implementation of the `TokenClassification` head can cause invalid tag sequences.
This PR turns nan to 0s for the `viterbi_tags` call.
=> Fix predicted tag sequence issues when logits become nans

setup.py
Bumps up the AllenNLP dependency to its newest version
=> Bump up allennlp version

setup.py, src/biome/text/dataset.py, tests/text/test_cli.py, tests/text/test_dataset.py
Bumps up the datasets version + removes gevent dependency
=> Bump up datasets version

src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/text_classification.py, tests/text/modules/heads/classification/test_document_classification.py
Adds dropout to the `DocumentClassification` head
=> Feat: Add dropout to the DocumentClassification

src/biome/text/dataset.py
The recently added methods all return a Dataset ... missed this slightly important part ...
=> Fix: newly added methods to Dataset

src/biome/text/configuration.py, src/biome/text/tokenizer.py
This adds the feature of splitting the input into sentences to our transformer tokenizer.
=> Feat: Add sentence splitting to the transformer tokenizer
