.gitignore, src/biome/allennlp/dataset_readers/__init__.py, src/biome/allennlp/dataset_readers/classification_dataset_reader.py, tests/allennlp/dataset_readers/test_biome_dataset_reader.py, tests/allennlp/dataset_readers/test_dataset_reader.py, tests/allennlp/dataset_readers/test_dataset_reader_forward.py, tests/allennlp/dataset_readers/test_parallel_dataset_reader.py, tests/resources/datasets/biome.csv.spec.yml
This is a first step to simplify the dataset readers.
It also updates the tests a bit.
- the idea is to tie them to the models -> they are named accordingly
- the names of the forward parameters are directly taken from the model's forward method
- the label field is identified by checking if it is optional in the model's forward method 
Follow-up MR will be:
- Update the ExamplePreparator
- Update tests properly
All tests pass locally for me.
@dvsrepo @frascuchon can you have a quick look at it? i would like to merge this soon, to update the ExamplePreparator next.
=> Simplify dataset reader

src/biome/data/sources/example_preparator.py
This reimplements the `metadata_file` option.
In the future this should go away, and its case should be covered by the `values_mapping` option.
=> Specify metadata_file field

src/biome/allennlp/dataset_readers/classification_dataset_reader.py, src/biome/allennlp/predictors/default_predictor.py, src/biome/allennlp/predictors/utils.py
I also registered a SequenceClassifier predictor to suppress the warning.
Remember:
- training uses the `read` (`_read`) method!
- predictor uses the `text_to_instance` method!
=> Make dataset reader compatible with predictor

src/biome/allennlp/dataset_readers/classification_dataset_reader.py, src/biome/allennlp/models/sequence_classifier.py, src/biome/data/sources/datasource.py, src/biome/data/sources/example_preparator.py, src/biome/data/sources/readers.py, src/biome/data/utils.py, tests/allennlp/dataset_readers/test_dataset_reader.py, tests/allennlp/dataset_readers/test_dataset_reader_forward.py, tests/allennlp/predictors/test_default_base_predictor.py, tests/data/sources/test_es_reader.py
Data sources handling  as `dask.dataframe`types.
Also avoid use of `ExamplePreparator` class inside `DataSource` since is a very coupled logic of `SequenceClassifierDatasetReader`. The `tokens`-`label` transformation are handled in dataset reader
=> refactor(datasource): manage data sources as tabular data

src/biome/allennlp/dataset_readers/sequence_classifier_dataset_reader.py, src/biome/allennlp/dataset_readers/sequence_pair_classifier_dataset_reader.py, src/biome/allennlp/models/__init__.py, src/biome/allennlp/models/sequence_classifier.py, src/biome/allennlp/models/sequence_pair_classifier.py, src/biome/allennlp/models/similarity_classifier.py
This PR adds a `SimilarityClassifier` model taking advantage of two loss terms (see: Deep Learning Face Representation by Joint Identification-Verification, https://arxiv.org/pdf/1406.4773.pdf).
It is fairly similar to the `SequencePairClassifier`.
I also aligned the three classifier model, maybe we could merge the `SequencePairClassifier` and the `SimilarityClassifier` in the future.
Some small fixes are also included.
=> Introduce the SimilarityClassifier Model

src/biome/allennlp/dataset_readers/sequence_pair_classifier_dataset_reader.py, src/biome/allennlp/models/sequence_pair_classifier.py
This PR is a work in progress for testing behaviour using `ListField` of `TextField` for tokens values instead of joining them into a single `TextField` 
This new Instance format requires some minimal changes in `SequencePairClassifier.forward` method. The main one is to calculate tensor mask and the pass through the embedder...
```python
mask = get_text_field_mask(tokens, num_wrapping_dims=1).float()
embedded_text = self._text_field_embedder(tokens, mask=mask)
```
...adding a new parameter `num_wrapping_dims` that I have no idea what it's mean. ;-)
Also, for the training process, we need adapt the trainer iterator configuration to this new Instance format, since the field used for sorting batches was `num_tokens`, calculated by `TextField` and no available for `ListField`. Instead of …
=> Use ListField instead of TextField for sequence pair classification problems

src/biome/allennlp/dataset_readers/mixins.py
`TextFieldBuilderMixin`: when some token data is not of type `str`, the `str.join` fails.
=> Fix concat non string values on reader

setup.py, src/biome/allennlp/commands/predict/predict.py, src/biome/allennlp/dataset_readers/__init__.py, src/biome/allennlp/predictors/default_predictor.py, src/biome/allennlp/predictors/utils.py, src/biome/data/sources/datasource.py, src/biome/data/utils.py
This PR fixes the predict command. The solution is basically to introduce a `DataSource.to_forward_bag` method.
Another big change is that we now use the same instance of the `predictor` for all partitions, instead of initiating a `predictor` in each partition.
The results can be seen here:
- http://ab4062a48abfd11e9af3a02c7f180c77-366616848.eu-west-1.elb.amazonaws.com/explore/prediction_validation_yml_with_balanced
- http://ab4062a48abfd11e9af3a02c7f180c77-366616848.eu-west-1.elb.amazonaws.com/explore/prediction_test_record_yml_with_record_output_3
=> Fix predict

src/biome/text/commands/learn/learn.py
This an attempt to reduce some of the larger and less relevant AllenNLP logs. This has two main limitations (and its related to one of the pitches for the coming cycle):
- Completely disables this logs, even for file logging stderr and stdout. I would argue that errors will still be raised, and we have the config.json with all the parameters. But of course best solution would be to dump all logs into file and minimize those shown in the training process.
- This is not configurable: users cannot say "I want all logs" when launching the command. I guess default is disable_logs, but users can enable this feature.
Could we discuss this briefly? I in any case would like to have this as a first attempt, even with the above limitations.
=> WIP: Disable lengthy AllenNLP logs

src/biome/text/commands/explore/explore.py, src/biome/text/dataset_readers/datasource_reader.py, src/biome/text/pipelines/pipeline.py
This PR solves problems with biome-ui showing label value as part of input data.
see 
The reason is that, using general signature as input information, the label field are included. We define a new predict_signature that will drop the optional parameters (and no required for inference)
=> Fix show label on ui

tests/text/dataset_readers/test_datasourcereader_children.py
This PR concludes [Pitch 41](https://gitlab.com/recognai-team/team/issues/41) by adding tests to the children of the `DataSourceReader`.
The *dataset_readers* test folder is quite a mess and i would like to adapt it to the new `DataSourceReader` approach, and move some stuff to *biome-data* where i think it actually belongs.
@dvsrepo @frascuchon What about the *test_parallel_dataset_reader.py* tests? Are they still needed?
=> Add tests to the children of the DataSourceReader

src/biome/text/commands/explore/explore.py, src/biome/text/interpreters/__init__.py, src/biome/text/interpreters/integrated_gradient.py, src/biome/text/models/base_model_classifier.py, src/biome/text/pipelines/pipeline.py, tests/text/models/base_classifier.py, tests/text/models/test_sequence_pair_classifier.py, tests/text/models/test_similarity_classifier.py, tests/text/pipelines/sequence_classifier_test.py
This PR introduces basic support for IntegratedGradient-based interpretation of classifiers based on text fields. It includes:
- overriding predictor get_gradients from allennlp predictor to make it return lists instead of a dict.
- extending IntegratedGradientInterpreter from allen to deal with lists and pack results with field names and tokens.
- add interpretation when running `explore` command (currently not working).
It is still based on the assumption that we have an ordered list of fields with the same order in which fields are passed through the embedding layers. If we move the responsibility to the pipeline of each model we could ensure this.
=> basic support for textfield interpret classifiers in explore ui

src/biome/text/commands/explore/explore.py
This PR just includes datasource and model as part of explore action attributes information.
It could be nice calculate basic model metrics  (F1, recall and precision) using some `dask.dataframe` directives and add them too.
@dcfidalgo @dvsrepo Should be possible?
=> feat: add datasource and model as part of explore attributes

src/biome/text/commands/learn/learn.py, src/biome/text/pipelines/pipeline.py
With this PR the verbose argument from the `biome learn` cli command is passed on to the `pipeline.learn` method.
=> pass on the verbose argument from the learn cli command to the pipeline

src/biome/text/pipelines/pipeline.py
With this small PR, we are able to use arbitrary registered `DatasetReader`s for `Pipeline`s. If in the pipeline config yaml no DatasetReader type is specified, the default type for the pipeline is taken. If a type is explicitly specified in the yaml, use this one instead.
This is particularly useful in the DZBank project.
=> allow arbitrary reader in pipeline if explicitly specified

src/biome/text/commands/learn/learn.py
in the pylint commit we removed the worker argument from the pipeline learn command, but passed it on in the learn cli command.
=> remove workers argument

src/biome/text/models/multifield_bimpm.py
This PR is an extensive update to the `multifield_bimpm` model born out of the DZ Bank project.
The new implementation allows a simple switch between `ListField` and `TextField` input, as well as the possibility of leaving out the backward matchers and adding a second encoding layer.
In a way it makes the `biome_bimpm` superfluous, but the `biome_bimpm` is a bit faster since we do not need so many if clauses. For this and backward compatibility issues, i left the `biome_bimpm` in the library.
=> implement new multifield_bimpm

src/biome/text/models/sequence_classifier_base.py, tests/text/models/base_classifier.py, tests/text/models/conftest.py
This PR adds a `loss_weights` parameter that allows one to give different weights to the labels in the CrossEntropyLoss function.
One has to specify the label name and its corresponding weight in the model config file. An example would be:
```yaml
architecture:
type: sequence_classifier
loss_weights:
'my_first_label': 0.2
'my_second_label': 0.8
text_field_embedder:
...
```
=> Feat: Implement loss weights for the SequenceClassifier and SequencePairClassifier

src/biome/text/commands/explore/explore.py, src/biome/text/constants.py, src/biome/text/dataset_readers/datasource_reader.py, src/biome/text/dataset_readers/mixins.py, src/biome/text/dataset_readers/text_transforms.py, src/biome/text/helpers.py, src/biome/text/models/sequence_classifier_base.py, src/biome/text/pipelines/defs.py, src/biome/text/pipelines/explore.py, src/biome/text/pipelines/pipeline.py, src/biome/text/pipelines/sequence_classifier.py, tests/text/dataset_readers/test_text_transforms.py
This PR include features for dummy classification pipeline initialization and pipeline output label extension.  This could be usefull for:
- Test pipeline transformations
- Extends labels for data annotation extension.
```python
from biome.text.pipelines import SequenceClassifierPipeline
pipe = SequenceClassifierPipeline.empty_pipeline(labels=["a"])
pipe.predict(features=["Nothing to annotate", "Buu"])
pipe.extend_labels("b", "c", "deee")
pipe.predict(features=["Nothing to annotate", "Buu"])
pipe.get_output_labels()
```
=> feat: empty model pipelines

examples/1.text_classifier/text_classifier.py, examples/2.document_classifier/document_classifier.py, examples/3.email_classifier/email_classifier.py, examples/4.language_model/classifier_from_scratch.py, examples/4.language_model/pretrain_lm.py, examples/5.ner/train_ner.py, src/biome/text/_impl_model.py, src/biome/text/configuration.py, src/biome/text/pipeline.py, tests/text/pipelines/test_bimpm.py
This PR brings discussion from #139, and define a set of rules for vocab creation/extension:
- `from_file`/`from_config` pipeline methods can load an already created vocab or creates/extends a vocab from provided datasources.
- No vocab param is passed to `Pipeline.train` method.
- The vocab extension pipeline is disabled as default.
```python
pipeline = Pipeline.from_file(
"text_classifier.yaml",
vocab_config=VocabularyConfiguration(
from_path=os.path.join(training_folder, "vocabulary"),
),
)
trained_pl = pipeline.train(
output=training_folder,
trainer=trainer_configuration,
training=train,
validation=validation,
extend_vocab=True,
)
```
Closes #139
=> better vocab extension/creation api definition

documentation/docs/documentation/02.tutorials/01.Training_a_text_classifier.md, documentation/docs/documentation/tutorials/Training_a_text_classifier.md, documentation/docs/nav.02.documentation/02.tutorials/01.Training_a_text_classifier.md, examples/1.text_classifier/text_classifier.py, examples/2.document_classifier/document_classifier.py, examples/3.email_classifier/email_classifier.py, examples/4.language_model/classifier_from_scratch.py, examples/4.language_model/finetune_classifier.py, examples/4.language_model/pretrain_lm.py, examples/5.ner/train_ner.py, src/biome/text/_configuration.py, src/biome/text/_helpers.py, src/biome/text/_pipeline_helper.py, src/biome/text/cli/train.py, src/biome/text/featurizer.py, src/biome/text/pipeline.py, tests/text/pipelines/test_bimpm.py
This PR include several changes over pipeline class definition and its inner dependencies.
The main `Pipeline` can only be initialized using the methods:
- `Pipeline.from_yaml`/`Pipeline.from_config`: for load a "blank" pipeline
- `Pipeline.from_pretrained` : for load already pretrained pipeline
There are to new inner `PIpeline` classes  managing the loading cases: `_BlankPipeline` and `PreTrainedPipeline`
Also, the `train`method in a pipeline doesn't not modify the original pipeline, so you can launch several training processes from the same pipeline. 
```python
train = "train.data.yml"
validation = "validation.data.yml"
training_folder = "experiment"
pl = Pipeline.from_yaml(
"text_classifier.yaml", vocab_path=os.path.join(training_folder, "vocabulary")
)
trainer_configuration = …
```
=> refactor: pipeline API & internal deps

src/biome/text/modules/heads/doc_classification.py
This PR concerns the mask in the `DocumentationClassification` after reducing the dimension by means of the `tokens_pooler`.
I stumbled across this one while designing the new BiMpm for records. The method we used so far (`get_text_field_mask`) only checks if the value of the tensor is `!= 0`, which is designed for TextField tensors with token ids. For tensors coming out of an embedder/encoder this is not reliable!
The new approach just checks if all tokens in a TextField are padding tokens and masks this TextField accordingly.
=> fix mask for the encoding after the pooling over the TextFields

src/biome/text/_model.py, src/biome/text/backbone.py, src/biome/text/modules/heads/bimpm_classification.py, src/biome/text/modules/heads/classification/defs.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/doc_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/record_classification.py, src/biome/text/modules/heads/text_classification.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py
A refactor following the discussion yesterday.
Also have a look at the new doc string for the `ModelBackbone` in case you any comments.
=> rename `BackboneEncoder` -> `ModelBackbone`

src/biome/text/backbone.py
Are the removed methods in this PR left overs of some earlier refactoring? Why not using directly the `tokenizer` methods?
=> Directly use `tokenizer` methods

src/biome/text/featurizer.py
Just a small refactor for consistency.
I would also immediately drop the backward compatibility for the `chars` and `words` keys in the config! Knowing us, we will forget to remove them in the end ... @frascuchon If you are ok with dropping them, i could push an extra commit to this PR.
=> adapt namespace values of WordFeatures and CharFeatures

src/biome/text/_model.py, src/biome/text/modules/heads/classification/defs.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/doc_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/text_classification.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py, src/biome/text/vocabulary.py
Just redefine vocabulary helper as module methods.
Also includes a new `_EmptyVocab` class for a early pipeline initialization
=> refactor: vocabulary helper as module

src/biome/text/_model.py, src/biome/text/modules/heads/classification/defs.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/doc_classification.py, src/biome/text/modules/heads/text_classification.py
This PR moves the calculation of the probabilities and other UI stuff to the `decode` method, that is only called for predictions.
@frascuchon I left one TODO about the duplicated information in `output.label` and `output.max_class`. I guess removing one or the other has implications for the UI, but we should only use one of the keys.
=> Move probabilities calculation to decode

src/biome/text/configuration.py
Small fix for default boolean params which were always `True` even when config was set to `False`.
=> Fix trainer config params bucketing and cache always True

examples/1.text_classifier/text_classifier.py, examples/1.text_classifier/text_classifier.yaml, examples/1.text_classifier/train.data.yml, examples/1.text_classifier/validation.data.yml, examples/2.document_classifier/doc_interpret.py, examples/2.document_classifier/document_classifier.py, examples/2.document_classifier/train.data.yml, examples/2.document_classifier/validation.data.yml, examples/3.email_classifier/email_classifier.py, examples/3.email_classifier/train.data.yml, examples/3.email_classifier/validation.data.yml, examples/4.language_model/classifier_from_scratch.py, examples/4.language_model/configs/train.data.yml, examples/4.language_model/configs/val.data.yml, examples/4.language_model/pretrain_lm.py, examples/5.ner/configs/train.data.yml, examples/5.ner/configs/validation.data.yml, examples/5.ner/train_ner.py, src/biome/text/_model.py, src/biome/text/backbone.py, src/biome/text/configuration.py, src/biome/text/errors.py, src/biome/text/modules/heads/defs.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/pipeline.py, src/biome/text/vocabulary.py, tests/text/pipelines/test_bimpm.py
This PR defines a better vocabulary creation flow. Includes two method to `Pipeline` class for this purpose.
For create or load a vocabulary for a "from-scratch" pipeline you can do as follow:
```python
pipeline = Pipeline.from_yaml("your_config.yaml")
pipeline.create_vocabulary(vocab_config=VocabularyConfiguration(....))
pipeline.train(....)
```
The vocab creation/load is not allowed for pretrained pipelines, raising an error.
Also, this flow restrict the vocab extension config (in training) only to pretrained pipelines, raising an error if you tries to extend a vocab for an "from-scratch" pipeline.
=> refactor: allow create and load vocabulary for pipelines from scratch

src/biome/text/helpers.py, src/biome/text/modules/heads/classification/defs.py
First version, still missing:
- Cleanup metric names to avoid tensorboard renaming during training.
- maybe simplify the get_metrics function with a helper function.
- @frascuchon @dcfidalgo I would like to make the per_label metrics configurable in classification heads, sometimes you don't want such level of detail and it makes very large logs, metric results files. But sometimes is very useful to have separate metrics for labels. I was thinking about a bool like `log_per_label_metrics` , what do you think?
=> refactor: use fbeta score to simplify metrics for classifiers

src/biome/text/modules/heads/classification/defs.py
Last label id was left out the per_label metrics calculation
=> fix: include ith label in metrics

src/biome/text/_model.py, src/biome/text/configuration.py
This PR resolves problems with word features configured with `lowercase_tokens` and vocabulary creation
=> fix(vocab): apply indexers configuration on vocab creation

src/biome/text/helpers.py, src/biome/text/modules/heads/classification/record_pair_classification.py, tests/text/modules/heads/test_record_pair_classification.py
Allennlp 1.0 includes changes in `TextField` tensors structures passed to `forward` method. 
In previous version, those tensors was dispatched in a dictionary, where the key references to the original feature name:
```python
{
"word": Tensor.....,
"char": Tensor.....
}
```
Now, there is a new indexation level. The reason is not quite clear, but some source code comments refers to integration with pretrained language models:
```python
{
"word": { "tokens" : Tensor.... } },
"char":  { "token_characters": Tensor... } }
}
```
This change impacts directly to `RecordPairClassification` and how it explains a prediction, since the token ids are calculated from those tensor structures.
This PR fixes problems finding token ids, taking in account this new format.
=> fix record pair classifier explain with allennlp 1.0

examples/1.text_classifier/text_classifier.py, examples/2.document_classifier/document_classifier.py, examples/3.email_classifier/email_classifier.py, examples/4.language_model/classifier_from_scratch.py, examples/4.language_model/finetune_classifier.py, examples/4.language_model/pretrain_lm.py, examples/5.ner/train_ner.py, setup.py, src/biome/text/_configuration.py, src/biome/text/_helpers.py, src/biome/text/_model.py, src/biome/text/cli/explore.py, src/biome/text/data/datasource.py, src/biome/text/helpers.py, src/biome/text/pipeline.py, tests/integration/test_text_classification.py, tests/text/modules/heads/test_record_pair_classification.py
In this PR the main change is that `Pipeline.train` and `Pipeline.explore`now also accept `DataSource`s instead of yaml files.
@frascuchon @dvsrepo Actually i would like to be a bit more radical and remove the option of passing on a yaml file path to these methods to keep the code simple and to "have only one obvious way to do stuff". Also, if you have a yaml file, you can always do:
```python
...
training=DataSource.from_yaml(path),
...
```
What do you think?
=> pipeline.train accepts `DataSource`s

src/biome/text/features.py, tests/text/test_configuration.py
This PR adds a test for the `PipelineConfiguration` class by comparing it to a yaml file when creating a Pipeline via `Pipeline.from_yaml` versus `Pipeline.from_config`.
@frascuchon Maybe you have some more ideas for additional asserts?
=> implement a `PipelineConfiguration` test 

src/biome/text/features.py, src/biome/text/pipeline.py
This PR implements basically two new methods:
- `Pipeline.to_dict()`
- `Pipeline.to_yaml()`
I am not 100% about the use case, but this allows you to do:
```
pl : Pipeline
pl_copy = Pipeline.from_yaml(pl.to_yaml("path/to/config.yaml"))
```
Also i did not fully understand why `WordFeatures` and `CharFeatures` are kind of a special case when calling `PipelineConfiguration.as_dict()`, so i did not touch this method directly.
=> implement `Pipeline.to_dict()` and `Pipeline.to_yaml()`

src/biome/text/_model.py
The current implementation failed since the key `word` is always present, but has the value `None` when no word feature is specified in the yaml file, for example.
=> do not set `weights_file = None` when no word feature is present

src/biome/text/_model.py
Test phase was failing with access to `cuda_devices[0]`.
=> fixes wrong cuda device setup test method

src/biome/text/pipeline.py, tests/integration/test_text_classification.py
When i wrote the integration test and also now the tutorials, i find myself writing something like this quite often:
```python
config_dict = {
"name": ...,
}
import yaml
pl = Pipeline.from_config(yaml.safe_dump(config_dict, allow_unicode=True))
```
I think it would be more useful for the `.from_config()` method to accept directly dict than a yaml formatted string.
=> `from_config` accepts dict instead of yaml formatted string

src/biome/text/featurizer.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/tokenizer.py
This PR adds an extra parameter to data featurization/tokenization for disable record dictionaries with record keys.
This behaviour can be interesting on record inputs without a fixed field structure. Removing the data keys from featurized data can inprove the trained model generalization.
This behaviour is applied to `DocumentClassification` and `TextClassification` forcing to use the`RecordClassification` for more strict data structures problems
=> feat(tokenizer): allow exclude record key on featurization

src/biome/text/_helpers.py
Fixes the pipeline method name when `Pipeline.explore` configures predictions cache folder
=> fix(explore): fix predictions cache method name

src/biome/text/_model.py, src/biome/text/modules/heads/classification/classification.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/modules/heads/task_head.py, src/biome/text/pipeline.py, tests/text/test_pipeline_model.py
This PR adds a default behaviour to `Pipeline.explain` method. 
If no explain was found/implemented, automatically generates an input tokenization as explain with no token attributions
Also, these changes exposes the number of steps (`n_steps`) for allow control attribution calculation (even deactivation if `n_steps` is less than 1.
=> feat(explain): default explain with input tokenization

src/biome/text/configuration.py, src/biome/text/pipeline.py
Just a small refactoring: this PR moves the `Pipeline.to_yaml()` method and `from_yaml()` logic to the `PipelineConfiguration`.
I think it is more explicit to write `my_pipeline.config.to_yaml()` than `my_pipeline.to_yaml()`, since you really just serialize the configuration, and not the whole pipeline with its model/weights. @dvsrepo would that be ok for you?
=> Move to_yaml/from_yaml logic to PipelineConfiguration

src/biome/text/_configuration.py
This PR fixes found problem with data index creation on explore method. Without this fix, the data index is created with no dynamic mapping configuration, bringing weird search problems
=> fix(explore): passing missing elasticsearch params for index creation

src/biome/text/_helpers.py, src/biome/text/helpers.py
This PRs applies a stringify conversion to input data for explore processes, avoiding problems with  multityping properties (a column/property containing values of different types - string and integer, for example)
=> refactor(explore): standardize input data as string data structs

src/biome/text/_helpers.py, src/biome/text/configuration.py
Using `BIOME_EXPLORE_ENDPOINT` env var value for configure and launching the explore access.
This is very useful when you access to your jupyter lab instance from other than localhost access
=> refactor(ui): use env var for explore endpoint

src/biome/text/_model.py, tests/text/test_pipeline_with_optional_inputs.py
As default, optional arguments are pipeline output candidates.
Here, if we have optional arguments as part of pipeline inputs definition, we discard them from output candidates
=> fix(output): discard optional args selected as input from pipeline output

src/biome/text/configuration.py, src/biome/text/tokenizer.py
This PR tries to resolve a TODO:
```
```
A `Tokenizer` is now instantiated with just a `TokenizerConfiguration`. In this way we avoid the duplication of every single argument in the two classes which can lead to errors when trying to sync them. In fact, two arguments were already missing in the `TokenizerConfiguration` ...
=> Pass on a TokenizerConfiguration to the Tokenizer

src/biome/text/about.py, src/biome/text/backbone.py, src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/helpers.py, src/biome/text/metrics.py
Another quick pass over the API doc strings.
The main additions are the TrainerConfiguration, WordFeatures and CharFeatures doc strings.
I am not sure if the arguments `cache_instances` and `in_memory_batches` are used at all at the moment, have to check this.
I also propose a slight change in the format: i would avoid specifying the type in the doc string, so this:
```python
def get_example(argument: int) -> str:
"""Gets an example name.
Parameters
----------
argument : int
An argument
Returns
-------
example : str
Name of the example
```
becomes this:
```python
def get_example(argument: int) -> str:
"""Gets an example name.
Parameters
----------
argument
An argument
Returns
-------
example
Name of the example
```
Since we consequently use type annotations the information is already in …
=> quick pass over API doc strings

src/biome/text/__init__.py, src/biome/text/pipeline.py, tests/text/test_pipeline_datasets.py
This PR 
- Adds a `quiet` train param for disable common logging info (keeping only warnings and errors)
- Logs to file training process logging messages
=> feat: quiet train and train logging file

src/biome/text/_helpers.py, src/biome/text/configuration.py, src/biome/text/helpers.py
This PR allows us to simplify the usage of ray tune's parameter choices.
For example: `tune.choice()` returns numpy types, and providing a `numpy.int32` as parameter for the hidden size fails, since it expects a python `int`.
=> sanitize input from ray tune for allennlp's from_params machinery

src/biome/text/_model.py, src/biome/text/pipeline.py, tests/text/test_pipeline_model.py
This PR adds a simple `Pipeline.predict_batch` method to process the input data as a batch.
I made a little comparison with the `Pipeline.predict()` method, and for a simple text classifier with 100 instances of a one token input, the `predict_batch` is 5-6 times faster. 
I would prefer to merge a simple `predict_batch()` version first, before adding further functionality (like batch_size, for example) in follow-up PRs.
As a side note: Depending on the input, using `predict` with the prediction cache can be much faster than `predict_batch`, just to keep this in mind.
=> Add `Pipeline.predict_batch` method

docs/docs/documentation/tutorials/Hyperparameter_optimization_with_Ray_Tune.ipynb, setup.py, src/biome/text/helpers.py, src/biome/text/loggers.py, src/biome/text/pipeline.py, tests/text/loggers.py
This PR adds a new train component: The training logger
This component adds extra functionality to EpochCallback's (indeed, its implementation is based on callbacks) since define init and end training mechanisms that callbacks doesn't 
Also implements a `MlflowLogger`  using this new component for mlflow train logging as experiment runs.
=> Feature: Train loggers integration

src/biome/text/_model.py
This PR adds descriptive error messages to the `predict`, `predict_batch` and `explain` method in case the model could not make a prediction for the provided input. This is only really useful when calling `Pipeline.explore()` that uses those methods under the hood. Closes #250
=> Add descriptive error messages for the predict/explain methods

src/biome/text/loggers.py, tests/text/test_loggers.py
Enable configure `run_name` and run tags for mlflow logger
=> feat(mlflow): logger accepts run name and tags

src/biome/text/_model.py, src/biome/text/pipeline.py
This PR is a small refactoring of the predict/explain methods:
- `explain` and `predict` use their corresponding `*_batch` methods
- A new helper function `_get_instances_and_predictions` avoids code duplication in the `predict_batch` and `explain_batch` methods.
- i copied the doc strings from the pipeline class, maybe there is a programmatic way to copy identical doc strings ?
=> [refactor] Avoid code duplication for predict/explain methods

src/biome/text/_model.py, src/biome/text/helpers.py, src/biome/text/pipeline.py, src/biome/text/vocabulary.py
With this PR you do not have to call `Pipeline.create_vocab()` if your features do not require it, that is if you only have a `transformers` feature (shortly discussed this with @dvsrepo this morning). Otherwise you would have to make an awkward call to `Pipeline.create_vocab()` with a basically empty argument:
```python
pipeline_dict = { ... }
pl = Pipeline.from_config(pipeline_dict)
pl.create_vocabulary(VocabularyConfiguration(sources=[]))
```
@frascuchon what do you think about the solution presented in this PR? I also left an inline comment.
=> Add transformers vocab on pipeline creation

setup.py, src/biome/text/_model.py, src/biome/text/backbone.py, src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/featurizer.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/tokenizer.py, tests/integration/test_text_classification.py, tests/test_tokenizer.py, tests/text/modules/heads/test_record_pair_classification.py, tests/text/test_configuration.py, tests/text/test_features_transformers.py, tests/text/test_loggers.py, tests/tutorials/test_tutorials.py
This PR tries to simplify integration with spacy at tokenization leve. By discarding all intermediate allennlp components, we gain in spacy dependency control and flow. This can be important for complex pipeline integrations (for data extraction) and some classification problems where tokenization affects to gold labels (Token classification)
=> Refactor: simplify spacy tokenization

docs/docs/documentation/tutorials/Training_a_sequence_tagger_for_Slot_Filling.ipynb, docs/docs/documentation/tutorials/Training_a_text_classifier.ipynb, src/biome/text/loggers.py, src/biome/text/pipeline.py, tests/integration/test_text_classification.py, tests/text/test_configuration.py, tests/text/test_pipeline_datasets.py
This PR adds a simple `WandBLogger`.
If the `wandb` module can be imported and if a login is detected, all training runs will be logged automatically to your wandb account.
=> Add WandBLogger

src/biome/text/_helpers.py, src/biome/text/configuration.py
This PR adds the `batches_per_epoch` argument to the `TrainerConfiguration`.
This option is useful if you want to validate more frequently on your validation data set during the training.
=> Add batches_per_epoch argument to TrainerConfiguration

tests/conftest.py
Just a small fix when running tests locally with the `wandb` client installed, see https://github.com/wandb/client/issues/1138
=> Fix tests when the wandb client is installed

tests/tutorials/test_tutorials.py
This PR removes the tutorial tests from the CI. The current fails are caused by the `pytest-notebook` package that is not actively maintained right now. Given this situation and the fact that these tests are quite heavy on resources, i vote for removing them from the CI and run them manually from time to time on our local machines (or even better on Colab), like once a month.
=> Skip tutorial tests in CI

src/biome/text/pipeline.py, tests/text/test_pipeline_explore.py
This PR fixes a bug when using a `DataSource` with no mapping in the `Pipeline.explore` method.
When following our first tutorial line by line, you do not stumble on this bug, since we add a mapping to the data sources when calling the `Pipeline.train` method. But when you skip the training, create a DataSource without mapping and feed this data source to the explore method, the bug appears.
=> Replace call to non-existent _default_ds_mapping attribute

src/biome/text/helpers.py, src/biome/text/modules/heads/task_head.py, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_token_classification.py
This PR introduces entities in the output of the `TokenClassification` if the input text is a `str`.
For now the format of the entities is: `{"start": int, "end": int, "label": str}`. This format is also used as "label input" during training.
=> Output entities for token classification

src/biome/text/features.py, tests/text/test_features_transformers.py
This PR adds the `max_length` parameter of AllenNLP's `PretrainedTransformerIndexer`/`*Embedder` to our transformers feature.
=> Add `max_length` parameter to transformers feature

src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/pipeline.py, src/biome/text/tokenizer.py, tests/text/test_configuration.py, tests/text/test_features_transformers.py, tests/text/test_pipeline_datasets.py, tests/text/test_pipeline_tokenizer.py
This PR introduces a `TransformersTokenizer` that enables us to directly process subword tokens usually used in the pretrained transformer models.
Until now, we bypassed a direct processing of subword tokens using AllenNLP mismatched indexer/embedder. With these changes here, if you only use the `transformers` feature, by default it will use the new `TransformersTokenizer` returning word pieces, and it will automatically use the matched indexer/embedder for the transformers feature.
This also allows us to use special tokens like for example the `CLS` token (used in many BERT-like models) for classification. You can check out the tests to see how to use the `bert_pooler` as pooler in our ClassificationHead.
The idea is that @ignacioct makes some comparisons between only subword tokens + …
=> Introduction of a TransformersTokenizer

Makefile, setup.py, src/biome/text/__init__.py, src/biome/text/_helpers.py, src/biome/text/configuration.py, src/biome/text/dataset.py, src/biome/text/pipeline.py, tests/resources/data/dataset_sequence.json, tests/text/test_dataset.py
This PR adds a new class `Dataset` intended to replace the current `DataSource`. It is basically a thin wrapper around HuggingFace's `datasets.Dataset` class enhanced by the for us crucial `to_instances` method, and a few convenient methods. See the advantages of this approach in #397 . 
In most cases i think we will use the `from_json` or `from_csv` class methods, but you have access to the whole `load_dataset` method, which is also used to create [HF datasets](https://huggingface.co/docs/datasets/loading_datasets.html). This gives us instant access to a lot of NLP datasets!
Indexing and iterating works directly with this class, but you have all the `datasets` utilities accessible via the underlying `dataset` attribute:
```python
from biome.text import Dataset
ds = …
```
=> Adding a Dataset class based on HuggingFace's datasets.Dataset

src/biome/text/configuration.py, tests/text/test_trainer.py
This PR adds the `use_amp` option to our `TrainerConfiguration` as requested in #356.
=> Add 'use_amp' option to the TrainerConfiguration

setup.py
This PR upgrade required pip version. Since we're using feature `--use-feature` in makefile directive and that feature is included since pip 20.2 version
=> fix(setup): upgrade required pip version

docs/docs/documentation/tutorials/2-Training_a_sequence_tagger_for_Slot_Filling.ipynb, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_token_classification.py
This PR simplifies token classifiers configuration. Only accepts labels values a span values, and internally converts into configured labels encoding.
=> refactor(token_classifier): config only accepts span labels

src/biome/text/_helpers.py, src/biome/text/pipeline.py, tests/text/test_pipeline_find_lr.py
This PR improves a bit the `Pipeline.find_lr` method. Instead of copying the whole pipeline, it saves the model state before the learning rate scan and restores it afterwards.
=> Avoid copy of pipeline when running a learning rate search

docs/docs/documentation/tutorials/3-Hyperparameter_optimization_with_Ray_Tune.ipynb, src/biome/text/hpo.py, tests/text/test_hpo.py
This PR introduces a new HPO class (`RayTuneTrainable`) that is compatible with Datasets and is intended to replace the `HpoParams` and `HpoExperiment` classes.
Personally i find it confusing that you can define the same parameters in the `tune.Experiment` and in `tune.run`, but the latter will be ignored if they were specified in the former. So the new implementation does not make use of the `tune.Experiment` and relies more on the parameters provided directly to `tune.run`. Also working with @ignacioct we noticed that it is more intuitive and faster to just copy the configs of your pipeline or trainer, and replace the parameters with the search spaces, than to write a new dict with only the search spaces. So the merging capabilities of the `HpoParams` are not really needed.
A minimal …
=> Adding a new HPO component, making is compatible with Datasets

MANIFEST.in, src/biome/text/_model.py, src/biome/text/modules/heads/task_head.py, tests/text/modules/heads/test_token_classification.py
This PR allow execute pipeline explain for token classification, processing `SequenceLabelField` and `MetadataField` fields types
=> fix: default explain not working for token classification

src/biome/text/helpers.py, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_token_classification.py
This PR fixes misaligned tokenization for `TokenClassifier` between `raw_text` and `tags`, when original text contains spaces symbols like `\n`.
=> fix(token-class): aligns raw text and tags tokenization

src/biome/text/_model.py, src/biome/text/dataset.py, src/biome/text/explore.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py, tests/text/modules/heads/test_token_classification.py, tests/text/test_dataset.py, tests/text/test_pipeline_with_optional_inputs.py
This PR splits  `labels` field in `TokenClassification` head in `labels` (tag labels)  and `entities` (span labels). Consequently, multiple output can be defined in pipelines, returning a list of names, instead of a single string.
=> refactor: using exclusive or outputs features for Token classifier

src/biome/text/dataset.py, src/biome/text/explore.py, tests/text/modules/heads/test_token_classification.py
This PR closes #415 
The `TokenClassification.featurize` will return None as instance if the spans cannot be aligned with the tokens. This lead to issues when these "instances" were passed on to the building of the vocab of the training.
We now skip those examples in `Dataset.to_instances` via the instance generator. We leave it to the head to make a meaningful logging of these examples. Maybe we could do the same for empty Instances, that is the head is responsible for checking that the instances that it returns make sense, otherwise it returns `None`.
=> Only return an Instance if the head did succeed in creating an Instance

src/biome/text/explore.py, src/biome/text/helpers.py, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_token_classification.py
This PR normalizes prediction data for token classification.
* All predictions contains `entities` and `tags` keys
* Non pre-tokenized predictions contains also `tokens` info
* `start` and `end` fields are dropped for pretokenized predictions
Also make `explore` works with multi-output heads
=> refactor:token classification prediction revision

src/biome/text/dataset.py, src/biome/text/helpers.py, src/biome/text/modules/heads/token_classification.py
This PR resolves a bug encountered by Dani and reported on slack (see https://colab.research.google.com/drive/1GHvOdjC4cesmWuZJgU3b_lGlOsT5m14Z?usp=sharing)
With the new `Dataset` class we serialize the instances via pickle in order to cache them **and** to allow for lazy loading. In the `TokenClassification` head we were putting `MetadataField`s with spacy `Doc` objects into the instances, and pickling/unpickling those instances took quite some time plus the cached instancese were >15GB big coming from a training set of ~1MB ... 
I refactored a bit the `TokenClassification` to avoid passing on a spacy Doc via the `Instance` itself.
The down side of the approach presented here is that for predictions of untokenized text, we create two times the same spacy Doc object:
- 1. For tokenizing …
=> No objects in instance meta

src/biome/text/loggers.py
We did not finish the WandB runs after the training, so the logged run time was wrong. This is a quick fix.
=> Finish wandb run when training ends

src/biome/text/explore.py, tests/text/test_dataset.py
This is the first in a series of PRs completely remove the `DataSource` class in our library (#404).
@ignacioct and I will take care of this providing alternately small PRs (changing at most 1 file) to make the review process easier and faster.
=> Remove DataSource from explore

setup.py, src/biome/text/dataset.py, src/biome/text/pipeline.py, tests/text/test_dataset.py
This PR is a follow-up PR of #442 
I found an intermediate solution for caching the instances. Instead of caching each Instance by itself, we can pickle the whole list of instances. Pickle is smart enough to deal with references to class instances, so the indexers are not a problem anymore.
The default behavior of `Dataset.to_instances` is now:
- Create and keep instances in memory + cache the whole list of instances on disk.
- Subsequent calls to `Dataset.to_instance` will reuse those cached instances and load them into memory. You can turn off this behavior by specifying `use_cache=False`.
- If `lazy=True`, lazily load data from disk and create instances on-the-fly
For now we loose the ability to multiprocess the instance creation (since we do not use the `Dataset.map` method anymore), …
=> Improve instance creation

src/biome/text/configuration.py, tests/text/test_loggers.py
Title says it all ... setting `num_serialized_models_to_keep: 0` in the `TrainerConfiguration` helps to reduce the disk footprint during the training, most notable in HPO experiment.
I also removed the `no_grad` argument that is used nowhere at the moment, and simplified a bit the `to_allennlp_trainer` logic.
=> Expose 'num_serialized_models_to_keep' argument in TrainerConfiguration

src/biome/text/dataset.py, src/biome/text/helpers.py
This PR just adds two convenient methods to `Dataset` and moves the `copy_sign_and_docs` decorator to the helper module.
=> Add `head` and `format` method to Dataset

src/biome/text/_model.py, src/biome/text/pipeline.py, tests/text/modules/heads/test_relation_classifier.py, tests/text/test_hpo.py, tests/text/test_pipeline_copy.py, tests/text/test_pipeline_datasets.py, tests/text_classification_integration_test.py
This PR switches to a "mutable" pipeline, that is training the pipeline modifies directly its weights instead the ones of a copy of the pipeline. It is a follow-up on the discussion here #410  .
I did some minor bench marking about memory consumption, and especially for big pretrained transformers this approach saves some memory depending on the size of the transformer (it was ~400 MB in case of the distilroberta_base). 
Since a mutable pipeline means that `_BlankPipeline` can be a `_PreTrainedPipeline` and `_PipelineCopy` is not needed anymore, i switched to only one `Pipeline` class. And one remark about `Pipeline.create_vocabulary`: i would like to get rid of this and make the vocab creation for a training as automatic as possible. If one wants some fancy vocab creation (most of the …
=> Introducing the mutable pipeline

src/biome/text/cli/cli.py, src/biome/text/cli/evaluate.py, src/biome/text/cli/serve.py, src/biome/text/cli/train.py, src/biome/text/pipeline.py, tests/text/test_pipeline_evaluate.py
This PR adds a `evaluate` method to our `Pipeline` reusing basically AllenNLP's evaluate function.
I am not sure anymore if we should use an evaluate method in our `explore` command, therefore i refrained from a more complex custom implementation.
For our UI we need several things that an "evaluation" does not necessarily provide:
- loss per instance (basically means batch_size = 1)
- attributes (from our `explain`)
On the other side, the metrics we get out of an evaluation are also not really interesting for the UI, since we calculate the metrics there on-the-fly applying the respective filters.
Additionally, now we use a "prediction cache" in the explore method that is not really compatible with an evaluate method.. 
@frascuchon Maybe we need another technical discussion about the …
=> Add a `Pipeline.evaluate` method

docs/docs/documentation/tutorials/4-Using_Transformers_in_biome_text.ipynb
This PR adds 4th tutorial about the *transformers* feature to our documentation.
The base of this tutorial was created in collaboration with @ignacioct , who also published this [very nice report](https://wandb.ai/ignacioct/biome/reports/Exploring-Ways-to-use-Pretrained-Transformers-in-biome-text--VmlldzoyNzk2MTM) on the WandB gallery as a direct result. You can find the tutorial here: https://github.com/recognai/biome-text/blob/feat/transformers_tutorial/docs/docs/documentation/tutorials/4-Using_Transformers_in_biome_text.ipynb
I am still not 100% happy, i think some minor things can be improved (for example, using `batches_per_epoch` instead of using a subset of the data for the HPO, or using some advanced search algorithm, since parallelizing the HPO in Google Colab is not possible due …
=> Introducing the transformers tutorial

src/biome/text/_helpers.py, src/biome/text/_model.py, src/biome/text/backbone.py, src/biome/text/configuration.py, src/biome/text/dataset.py, src/biome/text/features.py, src/biome/text/hpo.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/pipeline.py, src/biome/text/vocabulary.py, tests/text/conftest.py, tests/text/modules/heads/classification/test_record_pair_classification.py, tests/text/modules/heads/classification/test_relation_classifier.py, tests/text/modules/heads/test_language_modelling.py, tests/text/modules/heads/test_token_classification.py, tests/text/test_features_transformers.py, tests/text/test_hpo.py, tests/text/test_pipeline_copy.py, tests/text/test_pipeline_datasets.py, tests/text/test_pipeline_find_lr.py, tests/text/test_pipeline_vocab.py, tests/text/test_pipeline_with_custom_head.py, tests/text/test_pretrained_word_vectors.py, tests/text/test_trainer.py, tests/text_classification_integration_test.py
This PR removes the necessity of creating a vocab manually before the training. 
So in the most common use case you just have to create the pipeline, maybe a trainer config and then call the train method:
```python
pipeline = Pipeline.from_config(...)
trainer_config = TrainerConfiguration(...)
pipeline.train(...)
```
If you want more control over the vocab creation, you can pass in a vocab config:
```python
pipeline.train(..., vocab_config=VocabularyConfiguration(...))
```
The default value of vocab_config is basically `VocabularyConfiguration(datasets=[training_dataset])`.
If you set `vocab_config=None` the pipeline's vocabulary will be kept untouched, but i am not 100% sure about its use cases.
Now we basically always use the `extend_vocabulary` / `extend_vocab` method to extend our …
=> Automatic vocab creation

src/biome/text/dataset.py, src/biome/text/modules/heads/language_modelling.py, tests/text/test_pipeline_datasets.py, tests/text/test_pipeline_find_lr.py, tests/text/test_pretrained_word_vectors.py, tests/text/test_trainer.py
Makes the tests pass when running on a machine with a cuda device + fixes a cuda related bug in the `LanguageModelling` head
=> Make tests gpu safe + bugifx in language_modelling head

src/biome/text/dataset.py, tests/text/test_dataset.py
This PR allow select elastic document fields (`id`,  `_type` and `_index`) as selectable fields for `Dataset.from_elasticsearch` dataset features
=> feat(ds): select es document fields

src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/classification/test_relation_classifier.py, tests/text/test_configuration.py, tests/text/test_pipeline_tokenizer.py
After the tests we did with @ignacioct, this PR enables transformers for the Token and RelationClassification head by using the mismatched feature of AllenNLP.
If you know what you are doing and are an expert you can now also skip the configuration checks. This allows you to easily perform advanced tests, for example using word pieces in the heads mentioned above.
```python
from biome.text.configuration import PipelineConfiguration
PipelineConfiguration._SKIP_CHECKS = True
```
=> Allow transformers in Token/RelationClassification

.github/workflows/ci.yml
Deactivated manually for the 2.0.0 release, since i screwed this up on the testpypi server.
=> Reactivate testpypi in CI

.github/workflows/ci.yml, docs/docs/.vuepress/config.js, docs/docs/.vuepress/theme/styles/fonts.styl, docs/docs/documentation/tutorials/1-Training_a_text_classifier.ipynb, docs/docs/documentation/tutorials/2-Training_a_sequence_tagger_for_Slot_Filling.ipynb, docs/docs/documentation/tutorials/3-Hyperparameter_optimization_with_Ray_Tune.ipynb, docs/docs/documentation/tutorials/4-Using_Transformers_in_biome_text.ipynb, docs/prepare_versioned_build.sh
This is hopefully the final working solution for versioning our docs, including:
- correct links in the versioned tutorials
- fix font paths in all versions
It is basically all managed via the BIOME_TEXT_DOC_VERSION env variable and a small helper script in `docs/prepare_versioned_build.sh`. Check out our GitHub Action CI to see how to build and deploy a versioned version of our docs.
=> Fix tutorial versioning and doc fonts

src/biome/text/pipeline.py
This PR exposes the model parameters of the Pipeline. This allows us to easily freeze parameters before training, i give an example of how to do this in the method's doc string.
I used this method to try out the [BitFit](https://nlp.biu.ac.il/~yogo/bitfit.pdf) approach.
=> Expose model parameters

setup.py, src/biome/text/loggers.py, tests/text/test_loggers.py, tests/text/test_trainer.py
This PR solves issues if you do not have wandb installed but have a folder with the same name. We encountered this a few times now, so i finally fixed it. I also included some maintenance and little improvements here.
=> Log wandb data to `.wandb`

src/biome/text/_model.py, src/biome/text/modules/heads/__init__.py, src/biome/text/modules/heads/classification/classification.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/relation_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/task_head.py, src/biome/text/modules/heads/task_output.py, src/biome/text/modules/heads/task_prediction.py, src/biome/text/modules/heads/token_classification.py, tests/text/modules/heads/test_language_modelling.py, tests/text/modules/heads/test_token_classification.py, tests/text/test_pipeline_with_optional_inputs.py
This PR is basically a rewrite/refactor of the `TaskOutput` class. It became larger than expected, but i think the follow up PR combining predict/explain will become smaller because of this.
This is a rough list of all important changes:
- *task output* is now defined as output of a prediction; the output of the `forward` method is referred to as *forward output* through out the code
- `TaskOutput` is now a base class for specific output classes depending on the task; all output classes are *dataclasses*.
- these classes are located in `biome.text.modules.heads.task_output`
- the former `decode` method is replaced by a `make_task_output` method that works on an instance level, **not** batch level (this was recommended before by @frascuchon)
- the `forward` methods return a dict -> less …
=> Refactor/Rewrite of the `TaskOutput` class

src/biome/text/modules/heads/classification/classification.py, tests/text/modules/heads/classification/test_document_classification.py, tests/text/modules/heads/classification/test_text_classification.py
This PR fixes a bug where the TaskPrediction of the `ClassificationHead`s contain tuples instead of lists.
=> Bugfix: Tuples in classification output

src/biome/text/_helpers.py, src/biome/text/pipeline.py, tests/text/conftest.py, tests/text/test_pipeline_datasets.py
This PR is just a small refactoring/cleanup:
- reordered methods in the `Pipeline` class
- moved the init/end epoch callbacks to the `PipelineTrainer`
=> Refactor: Reordering pipeline methods

src/biome/text/pipeline.py, tests/text/test_pipeline_predict.py
With this PR a batch prediction (`Pipeline.predict(batch=...)`) always returns a list, **also** with length == 1.
=> Fix: Batch predictions always return a list

.github/workflows/ci.yml
Small improvement of our CI, by avoiding the upload of the docs build if not necessary.
=> CI: Only upload docs build if necessary

src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_classification.py, tests/text/modules/heads/classification/test_document_classification.py
This PR changes the input argument name of the `DocumentClassification` and `RecordClassification` head to match the `TextClassification` head: `document` -> `text`
=> change 'document' to 'text' + adapt tests

src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/modules/heads/task_head.py
This PR fixes an issue when using a transformer tokenizer and activating the `add_tokens`/`add_attributions` options in the `Pipeline.predict` method. The `end` key was taking into account the special chars added by the tokenizer, now it does not and refers correctly to the char index of the input.
=> Fix: Use token.idx_end if available

README.md, docs/docs/documentation/tutorials/1-Training_a_text_classifier.ipynb, docs/docs/documentation/tutorials/3-Hyperparameter_optimization_with_Ray_Tune.ipynb, docs/docs/documentation/user-guides/3-deployment.md, src/biome/text/cli/serve.py, src/biome/text/pipeline.py
This PR adds a `Deployment` section to the *User Guides* of the documentation. Goal is to describe two deployment options:
- built-in tool via our CLI and FastAPI
- deployment via MLFlow models
There is still little content and It's still a draft, @ignacioct maybe we could work together on this branch.
@dvsrepo in case you want to follow the progress and comment: checking out this branch and running `make docs` should provide you a preview of the docs.
=> Docs: Deployment section in our 'User Guides'

docs/docs/.vuepress/theme/components/AlgoliaSearchBox.vue
Title says it all ... After merging this PR, the master version of our docs should work fine, i still have to rebuilt the two other versions manually.
I still have to figure out how to dynamically add new versions to our algolia config file, for now we have to push a PR for every new release we want to add to the search.
=> Fix: Make Algolia search work with our versioned docs

src/biome/text/_model.py, src/biome/text/dataset.py, src/biome/text/featurizer.py, src/biome/text/modules/heads/classification/classification.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/relation_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/task_head.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py, tests/__init__.py, tests/text/modules/heads/test_token_classification.py, tests/text/test_model_predict.py, tests/text/test_pipeline_predict.py
With this PR the `Pipeline.predict` output can contain None. This is the case if for the provided input we cannot generate an instance, or the forward output cannot be converted into a `TaskPrediction` (less likely).
I added checks to the `TaskHead.featurize`s, that looks for empty TextFields, and if found the returned instance will be None. This indirectly catches empty string inputs, but be aware of tokenizers that add special tokens ... maybe i could add an explicit check for empty strings in the provided input.
Anyways, if you already know that for certain inputs the model will fail, i think it is more efficient to avoid sending this input to the model in the first place. @frascuchon let me know if you want me to add an explicit check for empty inputs in the heads.
=> Batch predictions can contain None 

src/biome/text/metrics.py, src/biome/text/model.py, src/biome/text/modules/heads/classification/classification.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/trainer.py, tests/text/modules/heads/classification/test_text_classification.py, tests/text/modules/heads/test_token_classification.py, tests/text/test_metrics.py
This PR adds the possibility of computing the validation metrics during an epoch. Before this was not possible because we only defined one set of metrics that was used to calculate the training and the validation metrics. For this i introduced a "helper" `Metrics` class that takes care of instantiating two identical sets of the metrics.
I also deleted our custom `MultiLabelF1Measure` to use the AllenNLP implementation, which gives us micro-, macro-averaged and per label metrics for free.
Includes also some minor bugfixes and tests.
Closes #526
=> Feature: Make metrics compatible with "inter-epoch" validations

src/biome/text/dataset.py, src/biome/text/trainer.py, tests/conftest.py, tests/text/test_loggers.py, tests/text/test_trainer.py
This PR adds three default loggers to our lightning trainer: CSV, TensorBoard, WandB. All of them can be disabled via `add_[csv, tensorboard, wandb]_logger` in the `Trainer` arguments.
=> Feat: Add default logger to our lightning trainer

docs/docs/documentation/tutorials/1-Training_a_text_classifier.ipynb, docs/docs/documentation/tutorials/2-Training_a_sequence_tagger_for_Slot_Filling.ipynb, docs/docs/documentation/user-guides/2-configuration.md, src/biome/text/_helpers.py, src/biome/text/configuration.py, src/biome/text/dataset.py, src/biome/text/loggers.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/pipeline.py, src/biome/text/trainer.py, tests/text/test_hpo.py, tests/text/test_pipeline_vocab.py, tests/text/test_pretrained_word_vectors.py, tests/text/test_trainer.py, tests/text_classification_integration_test.py
This PR closes #525 and optimizes the vocab creation.
Changes: The `VocabularyConfiguration` gets rid of its `datasets` parameter and is now a simple dataclass, the trainer gets a new argument: `include_valid_data_in_vocab`. In this way we can reuse the same InstanceDatasets for the vocab creation and the training.
=> Feat: Optimizing the vocab creation

setup.py
The pip version check does not really make sense and was implemented to "prevent" installation on Colab with an old pip version. But the env in colab is constantly changing, so it does not make much sense! 
In Colab at the moment, you have to uninstall torch1.8 manually before installing biome.text (we still need 1.7.1 because of allennlp) for biome.text to work ... i really should speed up the upgrade to allennlp2.0! Will make this my priority for the next week!
=> fix: Remove pip version requirement

docs/docs/documentation/tutorials/2-Training_a_sequence_tagger_for_Slot_Filling.ipynb, src/biome/text/configuration.py, src/biome/text/pipeline.py, src/biome/text/trainer.py, tests/text/test_pipeline_vocab.py, tests/text/test_trainer.py
This is a bit of a mess ...
The main change is the introduction of a `LightningTrainerConfiguration` dataclass (to be renamed when the old Trainer goes away). Until now it was (more similar to pure lightning):
```python
trainer = Trainer(**trainer_kwargs)
trainer.fit(pipeline, train_data)
```
Now it is: (more similar to hf transformers):
```python
trainer_config = TrainerConfiguration(**trainer_kwargs)
trainer = Trainer(pipeline, train_data, trainer_config)
trainer.fit()
```
I saw that i needed the pipeline and data to define sane defaults in the `Trainer` init, that is why i moved the trainer_kwargs to a proper dataclass. It is one line more, but i think it is worth it in order to have better defaults.
This PR also includes a minor change in the vocab config: i moved the …
=> Feat: Introducing LightningTrainerConfiguration

src/biome/text/configuration.py, src/biome/text/trainer.py
This PR adds a default early stopping callback to the lightning trainer, see #543 .
It also moves some of the lightning trainer params to an `extra_lightning_params` and refactors a bit the `LightningTrainerConfiguration`.
=> Feat: add early stopping by default to lightning trainer

setup.py, src/biome/text/__init__.py, src/biome/text/configuration.py, src/biome/text/model.py, src/biome/text/trainer.py, tests/text/test_trainer.py
This PR adds two parameters to the lightning trainer #543 (`warmup_steps` and `lr_decay`) to configure three types of learning rate schedulers: constant/linear/cosine scheduler with or without warmup. These are taken from the transformers library.
We cannot use the allennlp ones easily in lightning since they do not follow the pytorch scheduler API (to be fair there is not much of such an API ...). But you can still use all the pytorch schedulers manually, a small example is in the doc strings. Have to think about how we could improve this a bit.
=> Adds parameter for lr schedulers for the lightning trainer

src/biome/text/__init__.py, src/biome/text/configuration.py, src/biome/text/features.py, src/biome/text/trainer.py
At some point we deactivated all warnings, i think to avoid too many warnings from allennlp. Here i reactivate them again, since we are moving away from the allennlp trainer and i think they can be useful to spot some potential issues with the usage of third party libraries. When we encounter a frequent warning we should try to fix it or specifically deactivate that warning somehow.
This PR also includes some fixes that avoid warnings and their potential issues.
=> Activate warnings

src/biome/text/configuration.py, src/biome/text/tokenizer.py, tests/text/test_pipeline_tokenizer.py
This PR activates the `max_sequence_length` for the `TransformersTokenizer`.
=> Apply max_sequence_length also to the TransformersTokenizer

setup.py, src/biome/text/configuration.py, src/biome/text/helpers.py, src/biome/text/trainer.py, tests/text/test_features_transformers.py
With this PR, a `trainer_config.yaml` is saved together with the `model.tar.gz` and `metrics.json` file in the training output.
=> Save a `trainer_config.yaml` in the training output

src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/text_classification.py, tests/text/modules/heads/classification/test_document_classification.py, tests/text/modules/heads/classification/test_record_pair_classification.py, tests/text/modules/heads/classification/test_text_classification.py
This PR fixes an issue when using most of the classification heads with the new PL Trainer. It seems PL somehow stores the output dicts for all steps, so it is important not to "pollute" this dict with unnecessary stuff during the training!
=> Fix: Avoid huge memory overhead when using the Trainer

setup.py, src/biome/text/configuration.py, src/biome/text/helpers.py, src/biome/text/tokenizer.py, tests/text/modules/heads/classification/test_record_pair_classification.py, tests/text/modules/heads/classification/test_relation_classifier.py, tests/text/modules/heads/test_language_modelling.py
Our dependency on spacy is more direct than i thought. It is difficult for us to keep supporting spacy2.0 if we want to be compatible with spacy3.0:
- `Span.string` -> `Span.text`
- `spacy.gold` -> `spacy.training`, and also the method names changed (`offsets_to_biluo_tags` ...)
- no need to call `create_pipe` first, a simple `add_pipe` is sufficient
- no more model shortcuts
I vote for bumping up the spacy version and requiring spacy3.0 as this PR does (AllenNLP's spacy dep is >=2.1.0, <3.1.0). @frascuchon what do you think?
=> Bump up spacy to 3.0

src/biome/text/modules/heads/classification/text_classification.py, tests/text/modules/heads/classification/test_text_classification.py
Adds a `dropout` parameter to the `TextClassification` head allowing to introduce a dropout after the backbone and after the pooler.
=> Add dropout to the TextClassification head

src/biome/text/configuration.py, src/biome/text/tokenizer.py, tests/text/test_dataset.py, tests/text/test_pipeline_tokenizer.py, tests/text/test_tokenizer.py
This PR adds two new parameters to the `TokenizerConfiguration`:
- `min_sentence_length`
- `max_sentence_length`
These will only be used when setting `segment_sentences` to True.
=> Feat: Add min/max sentence length parameters

src/biome/text/featurizer.py, src/biome/text/pipeline.py, tests/text/test_pipeline_predict.py
We used to throw a PredictionError for single predictions or when the whole batch failed. We now simply return None and log a Warning.
=> Feat: Remove `PredictionError`, return None instead

src/biome/text/hpo.py, src/biome/text/pipeline.py, tests/text/test_hpo.py
I think we hardly used this argument, and i found a bug when using it with pretrained word vectors.
I will remove it for now, for the `TuneExperiment` class i will introduce a `vocab_config` parameter in a follow-up PR.
=> Remove the vocab parameter from Pipeline.from_config

src/biome/text/model.py, src/biome/text/modules/heads/classification/classification.py, src/biome/text/modules/heads/classification/doc_classification.py, src/biome/text/modules/heads/classification/record_classification.py, src/biome/text/modules/heads/classification/record_pair_classification.py, src/biome/text/modules/heads/classification/relation_classification.py, src/biome/text/modules/heads/classification/text_classification.py, src/biome/text/modules/heads/language_modelling.py, src/biome/text/modules/heads/task_head.py, src/biome/text/modules/heads/token_classification.py, src/biome/text/pipeline.py, tests/text/test_model_predict.py, tests/text/test_pipeline_predict.py
Adding a fallback prediction instead of returning a `None` object, helps inference service integrations with tabular oriented operations, like mlflow serving (expecting a dataframe as result)
=> refactor(inference): default fallback prediction

setup.py, src/biome/text/trainer.py, tests/text/test_trainer.py
=> Fix: create parent dirs when specifying an output_dir with Trainer.fit()
